# Generated by Django 4.0.1 on 2022-03-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoProject',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pavadinimas', models.CharField(max_length=50)),
                ('busena', models.IntegerField()),
                ('data', models.DateField()),
                ('aprasymas', models.TextField()),
                ('author', models.IntegerField()),
                ('author_name', models.TextField()),
                ('moderators', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='infoUAB',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pavadinimas', models.CharField(max_length=50)),
                ('busena', models.IntegerField()),
                ('tipas', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('numeris', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='projectUABs',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('UABid', models.IntegerField()),
                ('pavadinimasUAB', models.CharField(max_length=50)),
                ('projectId', models.IntegerField()),
                ('pavadinimasProject', models.CharField(max_length=50)),
                ('tipas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UABinfoTracker',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('UABid', models.IntegerField()),
                ('authId', models.IntegerField()),
                ('authName', models.CharField(max_length=20)),
                ('tekstas', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('projectsId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='toDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('busena', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SAP.infoproject')),
            ],
        ),
    ]
