# Generated by Django 4.0.1 on 2022-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproject',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='infouab',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectuabs',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uabinfotracker',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
