# Generated by Django 4.0.1 on 2022-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0002_alter_infoproject_id_alter_infouab_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uabinfotracker',
            name='busena',
            field=models.IntegerField(default=0),
        ),
    ]
