# Generated by Django 4.0.1 on 2022-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0002_auth_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
        migrations.AddField(
            model_name='infoproject',
            name='moderators',
            field=models.TextField(default=0),
        ),
    ]
