# Generated by Django 4.0.1 on 2022-03-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0003_uabinfotracker_busena'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouab',
            name='tekstas',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infouab',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='infouab',
            name='numeris',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infouab',
            name='pavadinimas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='infouab',
            name='tipas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projectuabs',
            name='pavadinimasProject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectuabs',
            name='pavadinimasUAB',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectuabs',
            name='tipas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uabinfotracker',
            name='authName',
            field=models.CharField(max_length=50),
        ),
    ]
