# Generated by Django 4.0.2 on 2022-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0004_infouab_tekstas_alter_infouab_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kodai',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('kodas', models.TextField(max_length=20)),
                ('kiek', models.IntegerField()),
            ],
        ),
    ]
