# Generated by Django 4.0.1 on 2022-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0005_kodai'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuabs',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectuabs',
            name='susisiekta',
            field=models.BooleanField(default=False),
        ),
    ]
