# Generated by Django 4.0.1 on 2022-02-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0005_alter_infoproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproject',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
