# Generated by Django 4.0.1 on 2022-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0006_alter_infoproject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproject',
            name='busena',
            field=models.IntegerField(),
        ),
    ]
