# Generated by Django 4.0.1 on 2022-02-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0007_alter_infoproject_busena'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproject',
            name='author_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
