# Generated by Django 4.0.1 on 2022-02-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0009_user_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoUAB',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pavadinimas', models.CharField(max_length=50)),
                ('busena', models.IntegerField()),
                ('tipas', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('numeris', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UABinfoTracker',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('UABid', models.IntegerField()),
                ('auth', models.IntegerField()),
                ('tekstas', models.TextField()),
            ],
        ),
    ]
