# Generated by Django 4.0.1 on 2022-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0010_infouab_uabinfotracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='uabinfotracker',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
