# Generated by Django 4.0.1 on 2022-02-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0011_uabinfotracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uabinfotracker',
            name='auth',
            field=models.CharField(max_length=20),
        ),
    ]
