# Generated by Django 4.0.1 on 2022-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0012_alter_uabinfotracker_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uabinfotracker',
            old_name='auth',
            new_name='authName',
        ),
        migrations.AddField(
            model_name='uabinfotracker',
            name='authId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
