# Generated by Django 4.0.1 on 2022-02-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0013_rename_auth_uabinfotracker_authname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectUABs',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('UABid', models.IntegerField()),
                ('projectId', models.IntegerField()),
                ('tipas', models.CharField(max_length=20)),
            ],
        ),
    ]
