# Generated by Django 4.0.1 on 2022-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAP', '0014_projectuabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuabs',
            name='pavadinimasProject',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectuabs',
            name='pavadinimasUAB',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
